-- Active: 1706506306585@@127.0.0.1@3306
-- remove any existing database if that database exists
DROP DATABASE IF EXISTS commonplace;
CREATE DATABASE IF NOT EXISTS commonplace;
USE commonplace;
DROP TABLE IF EXISTS Articles;
DROP TABLE IF EXISTS Authors;
CREATE TABLE IF NOT EXISTS Authors (
    AuthorID INT NOT NULL AUTO_INCREMENT,
    FirstName VARCHAR(15) NOT NULL,
    MiddleName VARCHAR(15),
    LastName VARCHAR(15) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    PRIMARY KEY (AuthorID)
);
CREATE TABLE IF NOT EXISTS Articles (
    ArticleID INT NOT NULL AUTO_INCREMENT,
    AuthorID INT NOT NULL,
    Content TEXT NOT NULL,
    PublishedOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ModifiedOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ArticleID),
    FOREIGN KEY (AuthorID) REFERENCES Authors (AuthorID)
);